x-build: &build
  build: .
  depends_on: [db, redis, mailpit]
  env_file: .env
  environment:
    - PORT=8000
    - DJANGO_DB_URL=mysql://demo:pass@db:3306/db_name
    - DJANGO_REDIS_URL=redis://redis:6379/0
    - DJANGO_DEBUG=false
    - DJANGO_EMAIL_HOST=mailpit
    - DJANGO_EMAIL_USERNAME=root
    - DJANGO_EMAIL_USERNAME=pass
    - DJANGO_EMAIL_FROM_ADDRESS=demo@djangoappname.com
    - DJANGO_EMAIL_FROM_NAME="${DJANGO_APP_NAME}"
    - DJANGO_EMAIL_TLS=true

services:
  db:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_USER=demo
      - MARIADB_PASSWORD=pass
      - MARIADB_DATABASE=db_name
    volumes:
      - db_data:/bitnami/mariadb
    healthcheck:
      test: ["CMD", "mariadb-admin", "-ppass", "ping"]
      timeout: 3s
      retries: 10

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8080:8025"
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1

  server:
    <<: *build
    ports:
      - "8000:8000"
  huey-worker:
    <<: *build
    command: pdm run python manage.py run_huey

volumes:
  db_data:
  redis_data:
