version: "3.8"
services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build: .
    command: python manage.py runserver 0.0.0.0:$DJANGO_PORT  --nostatic
    env_file:
      - .env
    environment:
      - DJANGO_DB_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on: [db]
    volumes:
      - static_files:/app/static
      - media_files:/app/media
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore: [.venv, node_modules, .db_data]
        - action: rebuild
          path: pyproject.toml

  proxy:
    image: caddy:alpine
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    depends_on: [server]
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - media_files:/app/media:ro

volumes:
  db_data:
  caddy_data:
  caddy_config:
  media_files: