[project]
name = "django_template"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Ankur Paudel", email = "ankur@paudel.me"},
]
dependencies = [
    "django>=5.0.6",
    "jinja2>=3.1.4",
    "django-vite>=3.0.4",
    "python-dotenv>=1.0.1",
    "whitenoise>=6.6.0",
    "django-debug-toolbar>=4.3.0",
    "celery[redis]>=5.4.0",
    "django-celery-results>=2.5.1",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
